apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-deployment
  labels:
    app: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: joeltompt/account-service:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: account-service-secrets